### ISSUE TITLE
Asynchronous loading

### ISSUE THREAD

**Issue by bmershon** [COMPSCI290-S2016/Group1_ImageSources#1]
The `scene` [here](https://github.com/COMPSCI290-S2016/Group1_ImageSources/blob/master/index.html#L110) is **undefined** because loadSceneFromFile executes synchronously (and returns nothing) while d3.JSON executes asynchronously and calls [`setupScene`](https://github.com/COMPSCI290-S2016/Group1_ImageSources/blob/master/SceneFile.js#L108) with the parsed JSON scene graph.

**Comment by ctralie** [comment]
Good catch.  Still seems to work loading the default scene in spite of that?  Or does it not work for you?

(If it still works I'll avoid changing it for now to avoid insanity pushing new code out to everyone)

**Comment by ctralie** [comment]
Actually, since I never call the scene object there (I only ever call glcanvas), I guess it's alright

**Comment by bmershon** [comment]
The rest of the flow doesn't seem to be affected, so no new release is necessary.

 I noticed this when I was trying to figure out what new methods and objects are added to the parsed JSON scene object. I viewed _index.html_ as being the possible "top level" to see the state of everything, but the flow of the program winds its way through _SceneFiles.js_ as well.

Sorry for the confusion!

**Comment by ctralie** [comment]
No problem!  Actually it was helpful for me because I think I remember not being able to use the scene object in index.html, and that explains why.  It also makes more sense to keep the scene object within the glcanvas, so that probably should have been a method of glcanvas.  Still working on my Javascript chops...
